// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kNsEFUoloGAMb6codK-gdfMY49Z9xZo',
    appId: '1:1043464595993:web:af6cf59f9f2543012c1888',
    messagingSenderId: '1043464595993',
    projectId: 'advmobprog-firebase-72968',
    authDomain: 'advmobprog-firebase-72968.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-72968.firebasestorage.app',
    measurementId: 'G-RQSNGGBV8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJ_RMuGsmzAkk0cNRigm9XE3dxzFBN70',
    appId: '1:1043464595993:android:c9c90fe25bca5ba62c1888',
    messagingSenderId: '1043464595993',
    projectId: 'advmobprog-firebase-72968',
    storageBucket: 'advmobprog-firebase-72968.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUM1KHlKQTr2FL_ckIv6oSeltCLWKfA40',
    appId: '1:1043464595993:ios:8c379f23a3cf16fe2c1888',
    messagingSenderId: '1043464595993',
    projectId: 'advmobprog-firebase-72968',
    storageBucket: 'advmobprog-firebase-72968.firebasestorage.app',
    iosBundleId: 'com.example.staanaAdvmobprog',
  );
}
